---
title: "Cleaning and Exploration"
---

## Data cleaning

Processes for cleaning and tidying data. Right now all processes are on mutiple jupyter notebooks under code/data_processing. Will be gathered together in this section.

Aliquam eu iaculis tellus, a lacinia lacus. Donec at placerat orci, suscipit maximus neque. Vivamus aliquet accumsan ultricies. Vivamus turpis mi, hendrerit nec massa vitae, ultricies laoreet ipsum. Cras et libero sem. Etiam at lectus ut lacus iaculis pretium. Phasellus cursus, justo in imperdiet commodo, justo odio commodo urna, in scelerisque diam dolor ac mauris. Fusce sapien tortor, dictum vitae nisi quis, rutrum faucibus est. Integer maximus eleifend efficitur. Nullam ut risus ac neque vehicula gravida et pulvinar orci. Curabitur nec hendrerit quam.

Fusce ac eleifend est, et scelerisque mauris. Aliquam dignissim sem id libero mattis varius. Integer tempus semper lacus eget eleifend. Aenean iaculis, dui in commodo pharetra, justo nisl porttitor ex, a posuere nisi erat sit amet enim. Nulla mattis nec dui ac convallis. Quisque gravida mauris sed posuere dignissim. Nam placerat nunc mattis ultrices scelerisque. Etiam lectus odio, cursus a neque a, consectetur dictum urna.
