project:
  type: website

website:
  title: "Walkability impact in D.C."
  navbar:
    left:
      - href: index.qmd
        text: Home
      - authors.qmd
      - conclusion.qmd
      - methods.qmd
format:
  html:
    code-fold: true
    embed-resources: true
    theme: 
    - zephyr
    - custom.scss
    css: styles.css
    toc: true